version: '3.7'
services:
  rubocop:
    build: .
    command: bundle exec rubocop
  test-unit:
    build: .
  test-rails-4.1:
    build:
      context: .
      dockerfile: Dockerfile-rails-4.1
  test-rails-5.0:
    build:
      context: .
      dockerfile: Dockerfile-rails-5.0
  test-rails-5.1:
    build:
      context: .
      dockerfile: Dockerfile-rails-5.1
  test-rails-5.2:
    build:
      context: .
      dockerfile: Dockerfile-rails-5.2
    command: bundle exec rails s -b 0.0.0.0
    ports:
      - 3000:3000
  test-rails-6.0:
    build:
      context: .
      dockerfile: Dockerfile-rails-6.0
